// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akqxzadyyrbmbifctafv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrcXh6YWR5eXJibWJpZmN0YWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzQ3NDEsImV4cCI6MjA2MjExMDc0MX0.b8YgtbE9QEbtYom_rHOdLuq-KbLwV-VrVgLLWY5K0GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);